/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TicketsRouteImport } from './routes/tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cloud': typeof CloudRoute
  '/copilot': typeof CopilotRoute
  '/emails': typeof EmailsRoute
  '/meetings': typeof MeetingsRoute
  '/tasks': typeof TasksRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cloud': typeof CloudRoute
  '/copilot': typeof CopilotRoute
  '/emails': typeof EmailsRoute
  '/meetings': typeof MeetingsRoute
  '/tasks': typeof TasksRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cloud': typeof CloudRoute
  '/copilot': typeof CopilotRoute
  '/emails': typeof EmailsRoute
  '/meetings': typeof MeetingsRoute
  '/tasks': typeof TasksRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cloud'
    | '/copilot'
    | '/emails'
    | '/meetings'
    | '/tasks'
    | '/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cloud'
    | '/copilot'
    | '/emails'
    | '/meetings'
    | '/tasks'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/cloud'
    | '/copilot'
    | '/emails'
    | '/meetings'
    | '/tasks'
    | '/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CloudRoute: typeof CloudRoute
  CopilotRoute: typeof CopilotRoute
  EmailsRoute: typeof EmailsRoute
  MeetingsRoute: typeof MeetingsRoute
  TasksRoute: typeof TasksRoute
  TicketsRoute: typeof TicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CloudRoute: CloudRoute,
  CopilotRoute: CopilotRoute,
  EmailsRoute: EmailsRoute,
  MeetingsRoute: MeetingsRoute,
  TasksRoute: TasksRoute,
  TicketsRoute: TicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
